<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon Condition="$([MSBuild]::IsOSPlatform('Windows'))"></ApplicationIcon>
    <AssemblyName>SAPGUN Media Grabber</AssemblyName>
    <RootNamespace>SapgunMediaGrabber</RootNamespace>
    <Version>0.3.0-alpha.2</Version>
    <InformationalVersion>0.3.0-alpha.2</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <AvaloniaNameGeneratorFilterByPath>__manual-control-lookup__</AvaloniaNameGeneratorFilterByPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAPGUN.MediaGrabber.Core\SAPGUN.MediaGrabber.Core.csproj" />
  </ItemGroup>
</Project>
